version: '2.1'
services:
  api:
    image: "danuk/shm-api:latest"
    restart: always
    links:
      - core
  core:
    image: "danuk/shm-core:latest"
    restart: always
    environment:
      #DEBUG: DEBUG
      TZ: ${TZ}
      LANG: C.UTF-8
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
      DB_HOST: mysql
      DB_PORT: 3306
    links:
      - mysql
	volumes:
      - ./shm/app:/app  
    depends_on:
      mysql:
        condition: service_healthy
  spool:
    image: "danuk/shm-core:latest"
    restart: always
    environment:
      #DEBUG: ERROR
      TZ: ${TZ}
      LANG: C.UTF-8
      SHM_ROLE: "spool"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
      DB_HOST: mysql
      DB_PORT: 3306
    links:
      - mysql
	volumes:
      - ./shm/app:/app  
    depends_on:
      mysql:
        condition: service_healthy
  admin:
    image: "danuk/shm-admin:latest"
    restart: always
    environment:
      SHM_URL: http://api
	volumes:
      - ./shm-admin/app:/app  
    ports:
      - "0.0.0.0:8081:80"
    links:
      - api
  client:
    image: "danuk/shm-client:latest"
    restart: always
    environment:
      SHM_URL: http://api
#    volumes:
	   - ./shm-client/app:/app
#      - ./styles-alternative.css:/app/assets/css/styles-alternative.css
#      - ./head.html:/app/ssi/head.html
#      - ./body.html:/app/ssi/body.html
    ports:
      - "0.0.0.0:8082:80"
    links:
      - api
  mysql:
    image: "mysql:8.0"
    restart: always
    environment:
      TZ: ${TZ}
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - "mysql-data:/var/lib/mysql"
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql-data:
    driver: local
